name: 'Terraform CI Workflow'

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Setup the required version of Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.0  # Set to the version you require

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init -input=false

      # Format Terraform configuration
      - name: Terraform Format
        run: terraform fmt

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate
