name: 'Terraform CI Workflow'

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Setup the required version of Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.0  # Set to the version you require

      # Initialize Terraform in the src/terraform directory
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: src/terraform

      # Format Terraform configuration in the src/terraform directory
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: src/terraform

      # Validate Terraform configuration in the src/terraform directory
      - name: Terraform Validate
        run: terraform validate
        working-directory: src/terraform